# Generated by Django 6.0.1 on 2026-02-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_name', models.CharField(max_length=30)),
                ('Bus_number', models.CharField(default=0)),
                ('Starting_point', models.CharField(max_length=40)),
                ('Ending_points', models.CharField(max_length=30)),
                ('features', models.TextField(max_length=100)),
                ('start_time', models.TimeField()),
                ('Reach_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=25)),
                ('mobile_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=10)),
                ('Seat_book', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.buses')),
            ],
            options={
                'unique_together': {('bus', 'seat_no')},
            },
        ),
    ]
