# Generated by Django 6.0.1 on 2026-02-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='no_of_seats',
            field=models.BigIntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seats',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses_seat_by_guru', to='bookings.buses'),
        ),
    ]
