# Generated by Django 6.0.1 on 2026-02-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_buses_no_of_seats_alter_seats_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='no_of_seats',
            new_name='total_seats',
        ),
    ]
