# Generated by Django 6.0.1 on 2026-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_no_of_seats_buses_total_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='Bus_name',
            new_name='bus_name',
        ),
        migrations.RenameField(
            model_name='buses',
            old_name='Ending_points',
            new_name='ending_points',
        ),
        migrations.RenameField(
            model_name='buses',
            old_name='Reach_time',
            new_name='reach_time',
        ),
        migrations.RenameField(
            model_name='buses',
            old_name='Starting_point',
            new_name='starting_point',
        ),
        migrations.RenameField(
            model_name='seats',
            old_name='Seat_book',
            new_name='seat_book',
        ),
        migrations.RemoveField(
            model_name='buses',
            name='Bus_number',
        ),
        migrations.AddField(
            model_name='buses',
            name='bus_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
