# Generated by Django 6.0.1 on 2026-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
