# Generated by Django 6.0.1 on 2026-02-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_buses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_no',
            field=models.CharField(max_length=40),
        ),
    ]
